# Generated by Django 3.1.7 on 2021-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easynet_api', '0003_auto_20210313_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creating_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
