# Generated by Django 3.1.7 on 2021-03-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easynet_api', '0005_auto_20210313_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creating_datetime',
            new_name='created',
        ),
    ]
