# Generated by Django 3.1.7 on 2021-03-13 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easynet_api', '0006_auto_20210313_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='Created'),
        ),
    ]
